# - Try to find the LIBYAML libraries

if(LIBYAML_INCLUDE_DIR AND LIBYAML_LIBRARIES)
    # Already in cache, be silent
    set(LIBYAML_FIND_QUIETLY TRUE)
endif(LIBYAML_INCLUDE_DIR AND LIBYAML_LIBRARIES)

if (NOT WIN32)
   include(FindPkgConfig)
   pkg_search_module(PC_LIBYAML REQUIRED yaml-0.1)
endif(NOT WIN32)

set(LIBYAML_INCLUDE_DIR ${PC_LIBYAML_INCLUDE_DIRS})

find_library(LIBYAML_LIBRARIES NAMES yaml HINTS ${PC_LIBYAML_LIBDIR} ${PC_LIBYAML_LIBRARY_DIRS})

mark_as_advanced(LIBYAML_INCLUDE_DIR LIBYAML_LIBRARIES)

